### ISSUE TITLE
nltk incompatibility?

### ISSUE THREAD

**Issue by Spiritdude** [ayoungprogrammer/nlquery#1]
I just tried to install it myself, and I encountered following issues:
- it seems `nltk` is missing in `requirements.txt`
- once I `pip install nltk` then `python main.py` errors with

```
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    main(sys.argv[1:])
  File "main.py", line 6, in main
    engine = NLQueryEngine('localhost', 9000)
  File ".../nlquery/nlquery/nlquery.py", line 21, in __init__
    self.parser = StanfordServerParser(host, port, properties)
TypeError: __init__() takes at most 3 arguments (4 given)
```

```
% python --version
Python 2.7.12
```

The CoreNLP server is running at port 9000 (tested via `wget`).

**Comment by ayoungprogrammer** [comment]
Sorry it looks like the lango version was incorrect. The version to be used is:

```
lango==0.13.2
```

I have updated the requirements.txt accordingly
